"""Add indexes to items table for performance

Revision ID: 9efe8a87fb75
Revises: 2b91c4d7021a
Create Date: 2026-07-07 22:55:04.246026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efe8a87fb75'
down_revision = '2b91c4d7021a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_category_goal', 'items', ['category', 'goal'], unique=False)
    op.create_index('idx_location_skill', 'items', ['location', 'skill_level'], unique=False)
    op.create_index('idx_price_category', 'items', ['price', 'category'], unique=False)
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_created_at'), 'items', ['created_at'], unique=False)
    op.create_index(op.f('ix_items_goal'), 'items', ['goal'], unique=False)
    op.create_index(op.f('ix_items_location'), 'items', ['location'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_price'), 'items', ['price'], unique=False)
    op.create_index(op.f('ix_items_skill_level'), 'items', ['skill_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_skill_level'), table_name='items')
    op.drop_index(op.f('ix_items_price'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_location'), table_name='items')
    op.drop_index(op.f('ix_items_goal'), table_name='items')
    op.drop_index(op.f('ix_items_created_at'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_index('idx_price_category', table_name='items')
    op.drop_index('idx_location_skill', table_name='items')
    op.drop_index('idx_category_goal', table_name='items')
    # ### end Alembic commands ###
